name: 3notaboutme
favicon: null
layout_spectrum: 0.7034842681605369
typography_spectrum: 0.8530913405120373
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d190f'
    - '#cdc9d9'
    - '#5d635d'
    - '#39372c'
    - '#9e9797'
  brandStrength: 0.75
  lightness: 0.375
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
