name: 3notaboutme
favicon: null
layout_spectrum: 0
typography_spectrum: 0.30729
title: "#3NOTABOUTme - Where It's Not About Me, It's About You"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74165701-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#578130'
    - '#0b1a08'
    - '#c4cf75'
    - '#789d7f'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
